# Generated by Django 3.1.2 on 2021-04-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='type_id',
        ),
        migrations.DeleteModel(
            name='FileType',
        ),
    ]
