# Generated by Django 3.2 on 2021-06-02 22:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointmodel',
            name='frame',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.imageframe'),
        ),
        migrations.AlterField(
            model_name='pointmodel',
            name='geo',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='pointmodel',
            name='pix',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326, unique=True),
        ),
    ]
