# Generated by Django 3.2 on 2021-05-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210506_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageframe',
            name='geoRefPolygon',
            field=models.TextField(blank=True, default=None, max_length=10000, null=True),
        ),
    ]
