# Generated by Django 3.1.2 on 2021-05-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ortophoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ortophoto',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='ortophotos/'),
        ),
    ]
