# Generated by Django 3.2 on 2021-06-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210602_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='pointmodel',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
