# Generated by Django 3.1.2 on 2021-04-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210427_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=10)),
                ('content', models.FileField(blank=True, default=None, null=True, upload_to='videos/')),
            ],
        ),
    ]
