# Generated by Django 3.1.2 on 2021-05-07 22:37

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210504_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topLeftCoordinate', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2)),
                ('bottomRightCoordinate', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2)),
                ('cell_size', models.PositiveIntegerField()),
                ('ortophoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ortophoto')),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2)),
                ('classification', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('avgColor', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]), size=3)),
                ('gird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.grid')),
            ],
        ),
    ]
