# Generated by Django 3.1.2 on 2021-04-30 15:16

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='content',
            field=models.ImageField(upload_to=main.models.video_frame_path),
        ),
    ]
