# Generated by Django 3.1.2 on 2021-05-07 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_grid_tile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='classification',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
