# Generated by Django 3.1.2 on 2021-05-22 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210522_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='classificationIndex',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
