# Generated by Django 3.1.2 on 2021-05-29 16:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_classification_classificationindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageframe',
            name='geoRefPolygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, default=None, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='tile',
            name='start_time_frame',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.imageframe'),
        ),
    ]
