# Generated by Django 3.1.2 on 2021-05-31 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210529_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='file_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.fileinfo'),
            preserve_default=False,
        ),
    ]
