# Generated by Django 3.1.2 on 2021-06-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_grid_file_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageframe',
            name='timestamp',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
