# Generated by Django 3.1.2 on 2021-06-01 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_imageframe_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='start_time_frame',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.imageframe'),
        ),
    ]
