# Generated by Django 3.1.2 on 2021-06-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210601_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='gridded_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='grids/'),
        ),
    ]
