version: '3.7'

services:
  db:
    image: "kartoza/postgis:13.0"
    container_name: firelab_db
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASS=firelabdbpass
      - POSTGRES_DB=firlab
      - POSTGRES_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql

volumes:
  postgis-data:
