version: '3.7'

services:
  db:
    image: "postgres:latest"
    container_name: firelab_db
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASS=firelabdbpass
      - POSTGRES_DB=firlab
      - POSTGRES_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: